### PR TITLE
fixed prefix so it has to be ascii

### PR DESCRIPTION
**Pull request by ds-David-Shen**

### CODE REVIEW

**Review by kevinjycui — CHANGES_REQUESTED** [review]
This is a bit long. I would suggest using `ord` to check if the prefix contains non-ASCII characters. Something like checking `all(ord(char) < 128 for char in fix)`
Also please comment out the `make_db` function in `connector.py`

**Review by ds-David-Shen — COMMENTED** [review]
Made the Ascii function shorter

**Review by kevinjycui — CHANGES_REQUESTED** [review]
Can you use `not` instead of `== False`? It's just better practice. Thanks!

**Review by kevinjycui — CHANGES_REQUESTED** [review]
Sorry, I forgot to mention this earlier but you should also check that fix is not None before checking if it is not ASCII (as done in the other elifs), since having the prefix as None is valid (it sets prefix back to default).

**Comment by ds-David-Shen** [comment]
Done

**Review by kevinjycui — APPROVED** [review]
Looks great. Thanks for contributing!

**Pull request merged**
